### ISSUE TITLE
Using # in the address

### ISSUE THREAD

**Issue by lov** [mrRay/OSCQueryProposal#23]
Although this has been discussed a bit in #21  I think its worth a dedicated topic since this is somehow important.

At the current state of the proposal the fragment URL - the last part of the URL after the # - used for requesting a single attribute, like http://ip:port/foo#VALUE.

Regarding to the HTTP docs (http://www.w3.org/Protocols/HTTP/Fragment/draft-bos-http-redirect-00.txt) the fragment value should not be sent to the server, but needs handling on the client side. Although this not a big issue, we can request http://ip:port/foo on the client side and get VALUE which could be posted toward to a delegate or something.

However, a great feature of using HTTP is we could use web browsers for querying which is not just cool for debugging, but could be useful for users too to discover a servers address space if they are using a client which does not support this OSC Query proposal. This feature won't work in browser for sure.

So, I suggest to use ? instead of # for this feature, which could be better for browsers, and fit better for the HTTP protocol too, since ? is used to identify a query in the URI RFC.

Any thoughts?

**Comment by tap** [comment]
agreee that ? instead of # would be a better choice and that sticking to idioms that are known from related technology spaces is desirable.

**Comment by mrRay** [comment]
howdy-

thanks very much for pointing this out, this was definitely a brain fart on my end- clearly, i don't do much web work :-P.  i've updated the proposal to reflect this, please let me know if you spot any other silly errors i made!

**Comment by lov** [comment]
no worries Ray, I don't do much web work either, that is why I let you know once I ran into this - never thought this could be a problem in the last couple of months :)
