### ISSUE TITLE
HTTP 1.1 implementation level

### ISSUE THREAD

**Issue by lov** [mrRay/OSCQueryProposal#24]
Hi there!

As we previously discussed HTTP seems the way to go with this proposal, which is an excellent idea. HTTP 1.1 seems the version we should support since it can (should) handle persistent connections. However, as you probably imagined the HTTP 1.1 specification is handling/requiring to handle a couple of circumstances/technologies which ones - at least in my opinion - make us to add some extra complexity which is not really needed - at least in my experience.

Here is the first problematic part, I'm sure there will be more soon:
## Chunked Transfer-Encoding

Both HTTP 1.1 clients and server MUST be able to handle chunked transfer encoding. Here is a good example about what is this, and it also shows a comparison with the classic "Content-Length:" way: http://www.jmarshall.com/easy/http/#http1.1c2

As I found, chunked transfer encoding has no upsides for us, but gives us a lot of complexity which should be handled, for the record, this site describes the benefits: https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Rationale

But, we always know - can't imagine a circumstance with a simple query/reply when this is not true -  the data size of the HTTP body we will send as a respond, so using the Content-Length attribute is a far more easier solution.

Any thought on this?

BTW, I'm started to working on an implementation a couple of days ago, so expect a some  questions/suggestion in the next coming days :)

**Comment by mrRay** [comment]
howdy-

it's been a while but if memory serves my main interest in chunked transfer-encoding with this project was to maintain a persistent connection (and then someone mentioned websockets and that seemed like a much better solution- and then you mentioned server-side events, which may obviate the need for all of this).  tamas, i can't think of any specific situations in this context which would require chunked transfer encoding either- but again, i have very little experience with network programming, so if anyone with such experience would care to chime in about the pitfalls of omitting support for this it'd be appreciated!

**Comment by lov** [comment]
As I see chunked transfer-encoding is really only used for dynamic content, but it seems to not our case. Anyway, I'd happy to hear other people thought on this too, especially if someone has already experience with this technologies!

**Comment by lov** [comment]
@jcelerier what are your thought on this? Do you find the need to handle chunked-transfer encoding on your side?

**Comment by jcelerier** [comment]
I don't see the need for chunked encoding to achieve tasks directly relative to oscquery ; it may be useful for streaming audio or things like this but at this point you are already using a proper protocol for this anyway.

The only case where it would make sense is for sending huge namespaces over slow connections, and even then I'm sure that it would be easier to allow support for compressed json than handle this.

**Comment by lov** [comment]
Great, thanks!
