### ISSUE TITLE
Defining what is the "root node"

### ISSUE THREAD

**Issue by lov** [mrRay/OSCQueryProposal#41]
Recently talking about some aspects of the protocol offsite with the OSSIA guys, and it turned out we are thinking about the root node differently, and I guess this could be confusing to others too, so I believe we should define what is the root node.

In my understanding, the root node is the top level object of an OSC address space, where all other address belongs. Here is an example which is valid in my opinion:

`
{
   "DESCRIPTION": "root node",
   "FULL_PATH": "/test",
   "CONTENTS": {
      ...
    }
}
`

Here, `/test` is the root node instead of `/`, because every other addresses in the deeper levels are belong to `/test` - in other words, the application address space always looks like `/test/....`

Am I right? Or the root node should be always `/`, like this:

`
{
   "DESCRIPTION": "root node",
   "FULL_PATH": "/",
   "CONTENTS": {
      ...
    }
}
`

But in this case, what is the real purpose of having a root node, if it should be always the same?

**Comment by jcelerier** [comment]
> Am I right? Or the root node should be always /, like this:

I think so; this it is what the OSC spec says (http://opensoundcontrol.org/spec-1_0) : 

    Each OSC Method and each OSC Container other than the root of the tree has a symbolic name, an ASCII string consiting of printable characters other than the following: [...]

It is also a symmetry with the GET query (`GET /`) of the http request, or D-Bus object paths, or Unix file paths.

But maybe the protocol could specify that the first "root (from the JSON point of view)" node answered in the 'GET /' request could be considered to be the actual root of the tree, so that the "root" part of the address could be hidden (since you know that you will be talking to this particular application on a given port anyway).

**Comment by lov** [comment]
>   But maybe the protocol could specify that the first "root (from the JSON point of view)" node answered in the 'GET /' request could be considered to be the actual root of the tree, so that the "root" part of the address could be hidden (since you know that you will be talking to this particular application on a given port anyway).

This is what I'm wondering about recently. A `GET /` request should be always results in the full tree in all circumstances, but from the JSON point of view should we present `/` all the time even if it only has one container?

**Comment by jcelerier** [comment]
> but from the JSON point of view should we present / all the time even if it only has one container?

That could be an optimization (I'm all for it :p) : return the json object corresponding to the actual root, since anyways we can get the whole OSC address to send to with the FULL_PATH.

**Comment by mrRay** [comment]
sorry, i'm not sure i fully understand this optimization- could you please give a quick example of how the output would differ with this change?

**Comment by jcelerier** [comment]
This is how I understand it : 
Without the optimization : `GET /` returns : 

    {
      "FULL_PATH": "/"
      "CONTENTS": [ 
        { 
          "FULL_PATH": "/myApp" 
          "CONTENTS": [ 
            {
              "FULL_PATH": "/myApp/opacity"
              "TYPE": "f"
              "DESCRIPTION": "Opacity of the sandwich"
            }
          ]
        }
      ]
    }
    
With the optimization, we gain a level : 

    { 
      "FULL_PATH": "/myApp" 
      "CONTENTS": [ 
        {
          "FULL_PATH": "/myApp/opacity"
          "TYPE": "f"
          "DESCRIPTION": "Opacity of the sandwich"
        }
      ]
    }

**Comment by lov** [comment]
I would not really call it as optimisation, but yes, this is it. Since all inside elements related to `/myApp` does it really make sense to have a `/` and call it as root node instead of saying `/myApp` is the root node?

**Comment by bltzr** [comment]
Just making sure I get it: what you're proposing is that, if there's only one element at the root, then there is a kind of "shortcut" that replaces /theRootNode for / in the reply ... right ? 
If so, I have two comments/questions:
- why not do that at every level where there is only one node, then ? 
- what if an app first has only one node at the root, and then, after a while, a second node is added... if we did so, that would change the whole structure, and move one level up the root for the same app
My impression is that this adds some complexity and possibilities of problems/errors for a minor benefit.
As we've been discussing offsite with Tamas, adding the app name as the only node at the root is a current practise, but several apps/systems don't do that, so my impression is that it's problematic to generalize something that is a particularity of some systems (even if they are a majority). 
Does that make sense ?

**Comment by lov** [comment]
> why not do that at every level where there is only one node, then ?

You actually that, check out the **http://ip:port/baz** example on the main page (https://github.com/mrRay/OSCQueryProposal).

> My impression is that this adds some complexity and possibilities of problems/errors for a minor benefit.

I must agree with that anyways, could be tricky to handle both circumstances on implementation level, and its better if we make strict expectations instead of making 2 possible ways to handle the same thing.

So, then, we all agree about `/` as the root node should be mandatory, right? :)

**Comment by bltzr** [comment]
> check out the http://ip:port/baz example
yes, in this case the request has been done by explicitly mentioning the 'baz' node, so that seems completely straightforward

>  So, then, we all agree about / as the root node should be mandatory, right? :)
so far, seems that we do - what about you @mrRay ?

**Comment by mrRay** [comment]
i think it would be simplest if we carried on with OSC's tradition of referring to "/" as the root node for the time being.  if this becomes onerous or a technical issue arises we can always revisit this optimization later!

**Comment by lov** [comment]
Great! Now as we all agreed, I'm going to close this ticket and revisit my implementation in Mitti :)
