### ISSUE TITLE
Same address, different OSC messages

### ISSUE THREAD

**Issue by anome** [mrRay/OSCQueryProposal#43]
Hi,

Maybe there is a solution, but so far, I didn't found it.
While implementing OSC-Query protocol, we realized that OSC messages seem to be identifier only by their addresses, while the parameters also matter.

I mean, in most code language, the signature of a method is its name and its parameters. So you can have two methods that share the same name, but have different parameters.
It's exactly the same with OSC : an OSC message isn't only an address, it's also its parameters. It's very useful for us and our users : for example, they can "launchOrStopColumn" by specifying an index (integer) or a name (string).

A solution could be to allow to pass CONTENTS as an array if needed (not only a dictionary).
To me, what's important is the "FULL_PATH" property to send OSC messages. The rest is just presentation : indeed, the JSON tree could be adpated to improve how OSC messages are shown to users.

Let me know if my explanations aren't clear.
Best. Philippe

**Comment by lov** [comment]
Thanks for bringing this to our attention. Although my personal opinion is using "launchOrStopColumnByIndex" and "launchOrStopColumnByName" results in less confusion and a better user experience, I totally understand the upsides of having a single "launchOrStopColumn" too.

But I guess the "launchOrStopColumn" commands are the same, and the only difference is their parameter type, I guess there is no reason to pass an other entry to CONTENTS, this circumstance more likely need to be addresses on entry level somehow - maybe just passing an array for TYPE with the corresponding format, like `"TYPE": ["i","s"]` - but this case we should check if TYPE is an array or not.

Looking forward for the opinions of others!

**Comment by jcelerier** [comment]
hi :) 

>  but this case we should check if TYPE is an array or not.

this would also likely have repercussions on other attributes such as `RANGE`: now every attribute has to be specified for the whole overload set which would certainly complicate a bit parsing.
Maybe a possibilty would be to have a "canonical" way to address a parameter, for instance in your case `/launchOrStopColumn i` and have a separate key specify overloads separately ? e.g. 

```JSON
{
   "FULL_PATH": "/launchOrStopColumn"
   "TYPE": "i"
   "RANGE": // etc...
   "DESCRIPTION": "Sending an int to this method does blah blah..."
   "OVERLOADS": [ 
      {
        "TYPE": "s",
        "DESCRIPTION": "Sending a string to this method instead does blah blah..."     
      }
   ]
}
```

this way, simple stuff stays simple (and does not change from the current sspec!), and complex stuff becomes possible.

**Comment by lov** [comment]
> this would also likely have repercussions on other attributes such as RANGE...

indeed this could add some unwanted complexity, thanks for pointing this out!

> have a separate key specify overloads...

Introducing a new OVERLOAD key sounds like a good solution for me.

> simple stuff stays simple (and does not change from the current spec!), and complex stuff becomes possible

I'm second on that! :)

**Comment by bltzr** [comment]
> simple stuff stays simple (and does not change from the current spec!), and complex stuff becomes possible
> 
> I'm second on that! :)
> 
+1 from here too !

**Comment by mrRay** [comment]
i added some language to the proposal to reflect this change, please take a peek at commit d2a44f489e34171d08210f02367c4389b5b242d3 and let me know if there are any changes you'd like to see in the specific wording!

**Comment by anome** [comment]
Thank you, it's great !
Maybe ALTERNATES would make more sense than OVERLOADS. But it's a detail.
