### ISSUE TITLE
Container that could be an OSC method

### ISSUE THREAD

**Issue by anome** [mrRay/OSCQueryProposal#44]
Hi,

So far, it seems that a container cannot be an OSC method. However, sometimes it happens.
Example :
- `/position` takes 2 floats as parameters
- `/position/x` only updates the X
- `/position/y` only updates the Y
- `/position/x/+` updates the X relatively (add or subtract a value to X)

How to represent this ? 
- setting `ACCESS` of node `position` to 2 (write) and assuming that the client would interpret this accordingly
- or creating a node with an empty address inside the node with address `position`

Thank you. Philippe

**Comment by jcelerier** [comment]
> So far, it seems that a container cannot be an OSC method. 

I don't think there is any counter-indication to this actually ? 

> setting ACCESS of node position to 2 (write) and assuming that the client would interpret this accordingly

I would say yes (if only because that's what happens in the ossia lib :p).

**Comment by lov** [comment]
> I don't think there is any counter-indication to this actually ?

But nothing indicates the opposite, am I right? The spec defines OSC methods and containers, but there is no indication that a container could be also a method. 

This is something which should be clearly stated in the specification.

>I would say yes (if only because that's what happens in the ossia lib :p).

Don't forget that `ACCESS` is an optional attribute so there is no guarantee it will be honoured.

**Comment by mrRay** [comment]
> "I don't think there is any counter-indication to this actually ?"

I'll be darned, there may be- a strict interpretation of the OSC spec could reach the conclusion that there is a functional difference between an OSC method and an OSC container, and since the rest of the spec references dispatching OSC messages to OSC methods, the implication is that containers are not valid targets for OSC messages.  Here's the bit I'm talking about:

> An OSC Server's OSC Methods are arranged in a tree strcuture called an OSC Address Space. The leaves of this tree are the OSC Methods and the branch nodes are called OSC Containers....The OSC Address of an OSC Method is a symbolic name giving the full path to the OSC Method in the OSC Address Space, starting from the root of the tree. An OSC Method's OSC Address begins with the character '/' (forward slash), followed by the names of all the containers, in order, along the path from the root of the tree to the OSC Method, separated by forward slash characters, followed by the name of the OSC Method. The syntax of OSC Addresses was chosen to match the syntax of URLs....When an OSC server receives an OSC Message, it must invoke the appropriate OSC Methods in its OSC Address Space based on the OSC Message's OSC Address Pattern.

For what it's worth, I've always had a more liberal interpretation of this passage- I've always assumed that OSC containers are valid dispatch targets for OSC messages.  Likewise, all the software I've written so far would work just fine with servers that expect client software to send messages to containers.  I don't know how prevalent that belief is among other developers...


> "How to represent this ?"

I'd do something like this:

```
"position" : {
	"TYPE" : "ff",
	"CONTENTS" : {
		"x" : {
			"TYPE" : "f",
			"CONTENTS" : {
				"+" : {
					"TYPE" : "f"
				}
			}
		},
		"y" : {
			"TYPE" : "f",
			"CONTENTS" : {
				"+" : {
					"TYPE" : "f"
				}
			}
		}
	}
}

```

**Comment by lov** [comment]
I'm totally okay with allowing containers as targets, just need to be clear in the specs this is actually supported.

> I'd do something like this:

Looks good for me. This way, basically if our parser find a TYPE in a container, we can assume that the contain's FULL_PATH is a valid OSC method.

**Comment by anome** [comment]
Thank you. Looks fine to me. 
We already understood and implemented OSC-Query like this in Millumin.
